// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 PANDA Coop

// Embeds build/bg_eik.wasm into src/wasm-bytes.ts as a base64 string,
// so the package needs neither fetch() nor fs to load the module.
import { readFileSync, writeFileSync } from 'node:fs';

const wasm = readFileSync(new URL('../build/bg_eik.wasm', import.meta.url));
const output = new URL('../src/wasm-bytes.ts', import.meta.url);

writeFileSync(
    output,
    [
        '// GENERATED by scripts/embed-wasm.mjs. Do not edit.',
        `export const WASM_BASE64 = '${wasm.toString('base64')}';`,
        '',
    ].join('\n'),
);

console.log(`embedded ${wasm.length} bytes of wasm`);
